{
  "apiVersion": "v1",
  "clusters": [
    {
      "cluster": {
        "certificate-authority-data": "${cert}",
        "server": "${endpoint}"
      },
      "name": "${name}"
    }
  ],
  "contexts": [
    {
      "context": {
        "cluster": "${name}",
        "user": "${name}"
        "namespace": "${namespace}",
      },
      "name": "${name}"
    }
  ],
  "current-context": "${name}",
  "kind": "Config",
  "preferences": {},
  "users": [
    {
      "name": "${name}",
      "user": {
        "token": "${token}"
      }
    }
  ]
}
