#@data/values
---
git_uri: git@github.com:blinkbitcoin/blink-infra.git
git_branch: kn/scrub_project
git_version_branch: testflight-name-prefix-uid-branch
github_private_key: ((github-blinkbitcoin.private_key))

deployments_git_uri: git@github.com:blinkbitcoin/blink-deployments.git
concourse_locks_git_uri: git@github.com:blinkbitcoin/concourse-locks.git

#! Not used?!
#! cepler_gates_branch: cepler-gates
#! cepler_gates_file: cepler-gates/infra.yml

docker_registry: us.gcr.io/galoy-org
docker_registry_user: ((docker-creds.username))
docker_registry_password: ((docker-creds.password))

testflight_gcp_creds: ((testflight-gcp-creds.creds_json))

#! Not relevant for Blink right now
#! testflight_azure_client_id: ((testflight-azure-creds.client_id))
#! testflight_azure_client_secret: ((testflight-azure-creds.client_secret))
#! testflight_azure_tenant_id: ((testflight-azure-creds.tenant_id))
#! testflight_azure_subscription_id: ((testflight-azure-creds.subscription_id))
#! testflight_azure_admins: ((testflight-azure-admins.users_json))

testflight_admins: []
testflight_ssh_private_key: ((testflight-ssh.ssh_private_key))
testflight_ssh_pub_key: ((testflight-ssh.ssh_public_key))
