#@data/values
---
deployments_git_uri: git@github.com:GaloyMoney/galoy-deployments.git
git_uri: git@github.com:GaloyMoney/galoy-infra.git
git_branch: main
cepler_gates_branch: cepler-gates
cepler_gates_file: cepler-gates/infra.yml
github_private_key: ((github.private_key))
docker_registry: us.gcr.io/galoy-org
docker_registry_user: ((docker-creds.username))
docker_registry_password: ((docker-creds.password))
concourse_tf_kube_host:  ((tf-backend-creds.host))
concourse_tf_kube_ca_cert:  ((tf-backend-creds.ca_cert))
concourse_tf_kube_token:  ((tf-backend-creds.token))
testflight_gcp_creds: ((testflight-gcp-creds.creds_json))
testflight_admins: ((testflight-admins.users_json))
testflight_ssh_private_key: ((testflight-ssh.ssh_private_key))
testflight_ssh_pub_key: ((testflight-ssh.ssh_public_key))
honeycomb_api_key: ((testflight-honeycomb.api_key))
staging_state_bucket: ((staging-gcp-creds.bucket_name))
staging_inception_creds: ((staging-gcp-creds.creds_json))
